### ISSUE TITLE
Renderer Requirements

### ISSUE THREAD

**Issue by fin-ger** [AreonDev/FreezingArcher#11]
# Renderer Requirements

This document should specify a high level API for the `FreezingArcher` renderer.
## Renderer specific properties of a material

A `Material` is described in the specification for a `World`.
If a property is set to `null` the corresponding rendering mechanism is disabled.
- Diffuse (`Color` or `Texture`)
- ParallaxMap (normal map `[R,G,B]` + height map `[A]`, `Texture`)
- Specular (specular colour `[R,G,B]` + specular intensity `[A]`, `Color` or `Texture`)
- Mirror (mirror colour `[R,G,B]` + mirror intensity `[A]`, `Color` or `Texture`)
- AmbientOcclusion (`Texture`)
- Light (light colour `[R,G,B]` + light intensity `[A]`, `Color` or `Texture`)
- Shadow (`Color` or `Texture`)
- Shader
  - If set to `null` the renderer will automatically determine which shader to use for this material. The renderer should determine the shader with the information from the above properties. The renderer may have a giant shader that can handle all the renderer specific properties of a material. If a combination of properties is often used (the mirror and light property could be `null` for most objects) the renderer shall recognize this and build a smaller version of the giant shader fitting those needs.
  - If not set to null the renderer may use the specified shader. This may be useful for particle systems or the like.
## Shader

A `Shader` may not be the shader itciself but an identifier identifying the shader. Therefore a shader may be registered in the renderer before using it in the code.

A `Shader` may be created from a `FileInfo` or a `string` describing the file location. In addition there should be a way to create a shader from source code.

The file format for a shader expected by the renderer looks like this:

``` xml
<shader>
    <vertex>path/to/vertex-shader.vsh</vertex>
    <fragment>path/to/fragment-shader.fsh</fragment>
    <geometry>path/to/geometry-shader.gsh</geometry>
    <tesselation>path/to/tesselation-shader.tsh</tesselation>
</shader>
```

> **TODO:**  Add structure of the shader source code
## Objects

Corresponding objects of the objects described below may be part a mid-level API in the renderer. The objects described in this sections are identifiers and part of the high-level API.
### Texture

A `Texture` may not be the texture itself but an identifier identifying the texture. Therefore a texture may be registered in the renderer before using it in the code.

A `Texture` may be created from a `FileInfo` or a `string` describing the file location.
### CubeTexture

A `CubeTexture` may not be the texture itself but an identifier identifying the texture. Therefore a texture may be registered in the renderer before using it in the code.

A `CubeTexture` may be created from 6 `FileInfo` objects or 6 `string` objects describing the file locations for `Up`, `Down`, `Left`, `Right`, `Front` and `Back` texture.
### Texture3D

A `Texture3D` may not be the texture itself but an identifier identifying the texture. Therefore a texture may be registered in the renderer before using it in the code.

A `Texture3D` may be created from a number of `n` `FileInfo` objects or a number of `n` `string` objects describing `n` file locations. All given files may be images of the sames size.
### Color

A `Color` consists of 4 `float` properties in range from `0` to `1`. Each float is describing one of the colour channels `[R,G,B,A]`.
## Camera

A `Camera` may not be the camera itself but an identifier identifying the camera. Therefore a camera may be registered in the renderer before using it in the code.

A `Camera` may be managed by a manager. The manager should be aware of groups. Each camera shall be assigned to a group. A `Group` could contain multiple instances of `Group` objects. Those are handled as subgroups. The user should be able to switch through the camera groups. An example could be the switching between `FirstPersonCamera`, `ThirdPersonCamera` and `ThirdPersonFrontCamera`. Those could be a `Player` camera group.

A `Camera` may be created from `NearClip`, `FarClip`, `FieldOfView`, `InitialViewDirection` and `RotationPoint` parameters.
## Model

A `Model` may not be the model itself but an identifier identifying the model. Therefore a model may be registered in the renderer before using it in the code.

As a `Model` is quite a complex object only the basics will be listed here. The `Model` may be extended later on.

A `Model` may be created from a `FileInfo` object or a `string` object describing the file location. In addition a `Model` may be created from a `VertexArray` and an `IndexArray`.

The file format used to describe a model looks like this (may be extended later on):

``` xml
<model>
    <object>path/to/my-model.obj</object>
</model>    
```
### Rigid Model
- Meshparts
### Meshpart
- Material
- Buffer
- Bones
- Parent bone

The `Renderer` may choose an effects class from the information given in the `Material`.
### Buffer
- Vertex buffer
- Index buffer
### Bone

``` c#
public class Bone
{
    // Weight of each Vertex
    public float[] VertexWeights { get; protected set; }

    // `Vertex` id's describing a vertex
    public uint[] Vertices { get; protected set; }

    // if null this bone is root
    public Bone ParentBone { get; protected set; }

    // Array of child bones
    public Bone[] ChildrenBones { get; protected set; }

    public Matrix[] KeyTransform { get; protected set; }

    public TimeStamp[] KeyTimestamp { get; protected set; }
}
```
## Deferred shading

Use deferred shading to compute shadows with many objects with moderate computational effort.
## Deferred lighting

Use deferred lighting to lower the impact on the performance when having light emitting materials.
Lighting system should support:
- directional lighting
- specular lighting
- spotlights
- light emitting surfaces
## Compositor

Compositing is a process which is executed after rendering is finished. The input of the compositor is the result of the rendering process, such as color map, depth map, normal map etc. 
Additionally the compositor can take external inputs, such as arrays, structures etc.
The structure of the compositing is a graph, which should be compiled to a single shader after resolving the dependencies of the steps. 
## Notes for implementation
- all of the above points should be implemented with optimized performance
- usage of buffers and other accelerated techniques is recommended
- do only as little as possible changes to the statemachine and use optimized things like vertex array objects

**Comment by martin31821** [comment]
## Global Organization
As we already discussed, we want to organize rendering scene-based, where each scene has it's own set of resources and managers, so we can control resource loading and freeing per-scene and use global caching.

## Model Management

I think, our management of models (not only models, but textures, shaders etc., as those objects and the data behind are widely used across multiple scenes) should be organized in 4 components:
* A global cache, which is used to cache widely used data (only one object of this type exists)
* A manager, which manages which objects are used in which scene and arranges the data to allow efficient rendering of it (one object of this type exists per Scene)
* Multiple object classes, which represent the **type** of the objects (one object per model type per scene)
* Instance classes, which represent a certain **instance** of a **type** of a model. 

So the complete structure is a tree, which is visualized below:
(GitHub image uploading broken, I will post it later)

**Comment by martin31821** [comment]
![image](https://cloud.githubusercontent.com/assets/5557633/6908216/dc1d4d24-d73b-11e4-86a2-a36cbe05cd1d.png)

**Comment by fin-ger** [comment]
## Effect classes

* Wood
* Stone
* Metal
* Plastic
* Clothes

One Effect has one `Shader` and `n` instances of `Material`.

## Compositor

* Effects
 * Glass
 * Water
* Slpitt effects *??*
 * Alpha
 * RGB
 * Depth
 * Normal
* Post processing effects
 * Deferred lighting
 * Deferred shading
 * Blur
 * FXAA
 * HDR
 * Glow
 * Fire
 * Rain

## Material optimization

Every texture which can be attached to a material is stored in a texture array in the corresponding effect class.
There is a texture array for diffuse color which has `n` entries for `n` materials which all belong to the effect class `Wood`. As we are willing to prevent empty texture slots we store the textures consecutively and access them via an index. The indices are read from the material parameters. We store the material parameters as a uniform buffer, as a shader storage buffer or in an one dimensional texture.

Comparison when having 4 Materials in an effect class:
```
Without optimization:
Diffuse  [X,X,X,X]
Specular [X, ,X, ]
Parallax [ , , ,X]

With optimization:
Diffuse  [X,X,X,X]
Specular [X,X]
Parallax [X]
Indices  [0, 0,-1, // texture indices of first material
          1,-1,-1, // texture indices of second material
          2, 1,-1, // texture indices of third material
          3,-1, 0] // texture indices of fourth material
          |  |  |_ Parallax
          |  |_ Specular
          |_ Diffuse
```
As we can see this saved `5` texture slots and therefore lots of memory.
