### ISSUE TITLE
World Specification

### ISSUE THREAD

**Issue by fin-ger** [AreonDev/FreezingArcher#12]
# World Specification
### Weather

The `Weather` object is describing the global weather in this world.
Properties of the `Weather` are:
- `Temperature`
- `VisibilityRange`
- `Cloudiness`
- `Downfall`
  - `Sunshine`
  - `Rain`
  - `Snow`
  - `Thunderstorm`
- `Wind`
- `Sunrise`
- `Sunset`
### Time

The `Time` object hold the worlds daytime and a date.

Properties of the `Time` are:
- `Daytime` in game time
- `Date` in game time
- `LengthOfDay` in real time seconds
### Sun and moons

We should be able to simulate one sun and many moons.
- `Position`
- `Color of emitted light`
- `Sunrise`
- `Sunset`
- `Orbit`
### Material

A `Material` has a section for `Renderer` specific properties, `Audio` specific properties and `Physics` specific properties.

`Renderer` specific properties:
- `Diffuse`
- `ParallaxMap`
- `Specular`
- `Mirror`
- `AmbientOcclusion`
- `Light`
- `Shadow`
- `Shader`

`Audio` specific properties:
- `StepSound` and `StepSoundGain`
- `HitSound` and `HitSoundGain`
- `Density`
- `Diffusion`
- `Gain`
- `GainHF`
- `GainLF`
- `DecayTime`
- `DecayHFRatio`
- `DecayLFRatio`
- `ReflectionsGain`
- `ReflectionsDelay`
- `LateReverbGain`
- `LateReverbDelay`

`Physics` specific properties:
- `FrictionFactor`
- `Stiffness`

A `Material` may be created from a `FileInfo` object or a `string` objects describing the file location.

The file format for a material looks like this:

``` xml
<material>
    <!-- if attribute not available the default will be used -->
    <graphics diffuse="path/to/diffuse.png"
              parallax="path/to/parallax.png"
              specular="path/to/specular.png"
              mirror="path/to/mirror.png"
              ambient-occlusion="path/to/ambient-occlusion.png"
              light="path/to/light.png"
              shadow="path/to/shadow.png"
              shader="path/to/shader.xml" />

    <audio step-sound="path/to/step-sound.ogg"
           step-sound-gain="1.0"
           hit-sound="path/to/hit-sound.ogg"
           hit-sound-gain="1.0"
           density="1.0"
           diffusion="1.0"
           gain="1.0"
           gain-hf="1.0"
           gain-lf="1.0"
           decay-time="5.0"
           decay-hf-ratio="1.0"
           decay-lf-ratio="1.0"
           reflections-gain="1.0"
           reflections-delay="5.0"
           late-reverb-gain="1.0"
           late-reverb-delay="3.0" />

    <physics friction-factor="4.0"
             stiffness="2.3" />
</material>
```

---

> This document is not finished yet. Feel free to add some information.

**Comment by martin31821** [comment]
## How to design an entity (with components, semi dynamic, good performance)

We have an entity base class which holds an array of components. Each component is of type FAObject (see Performance tweaks #7) and has therefore a 16bit identifier which is an unique identifier of the type. The TypeIdentifier is used to generate the key for the array of components.
Then we need to create a method to access certain components, best way for this is to get any component in O(1). We want to have this as 
```c#
public T Get<T>();
public T Get<T>(ushort TypeIdentifier);
```

After this the postprocessor must ensure that any call to Get is made with a valid type parameter (which must inherit from FAObject) and after that transform the calls to Get() into calls to Get(ushort) with the typeIdentifier inserted as argument.

Furthermore the postprocessor must ensure that the array size of the component array fits to the needs of the inserted components (not too big, not too small. maybe we should let the build fail if we have an untypical combination of TypeIds)

**Comment by fin-ger** [comment]
## Entity Component System
![freezingarcherentitycomponent](https://cloud.githubusercontent.com/assets/5300274/7053166/641bfef2-de33-11e4-8cc3-499b808fe19d.png)
