### ISSUE TITLE
Math Library

### ISSUE THREAD

**Issue by martin31821** [AreonDev/FreezingArcher#18]
As we discussed we need the following things for an math library:

* Vector[2,3,4][f,i]
* 4x4 Matrix
* Quaternions

Furthermore we would like to be able to do this things:
* Operators
* trigonometric functions (sin, cos tan, etc.)
* base math functions (length, lengthsquared, etc.)
* GLU Matrix
* Matrix x Vector
* Matrix x Quaternion
* Convex Hulls
* maybe we need SSE/SIMD support (wait for ryujit, use Mono.Simd, use Yeppp! or other things??)

**Comment by fin-ger** [comment]
implemented
