### ISSUE TITLE
Input: Keys are hanging and Consumers are not getting the right keys

### ISSUE THREAD

**Issue by DavidB3** [AreonDev/FreezingArcher#27]
Bunny not moving -> Consumer is not getting its keys
On the other hand Willy's cam seems to work..
Consumers are in Main.cs and MyFirstFr[....].cs

**Comment by fin-ger** [comment]
Checking this, worked yesterday - currently searching for the code

**Comment by fin-ger** [comment]
Ok, the cam is just moving too fast. You are not recognizing the movement of the bunny as the bunny is moving too slow.
